// Auto-generated by `tsx src/bin/export-demo.ts`. Real digests baked in
// so /demo works on serverless deployments without persistent DB.

import type { DigestBody, Urgency } from "./types";

export interface DemoDigest {
  id: number;
  competitor: { id: number; name: string; domain: string };
  period_start: string;
  period_end: string;
  urgency: Urgency;
  body: DigestBody;
  created_at: string;
}

export const DEMO_DIGESTS: DemoDigest[] = [
  {
    "id": 2,
    "competitor": {
      "id": 1,
      "name": "Linear",
      "domain": "linear.app"
    },
    "period_start": "2026-05-04T22:07:27.557Z",
    "period_end": "2026-05-11T22:07:27.557Z",
    "urgency": "high",
    "body": {
      "summary": "Linear has introduced 'Releases' for planning and tracking software releases, integrated with CI/CD tools, and significantly expanded its AI capabilities with 'Linear Agent MCP support' allowing connection to external tools. The homepage has been updated to reflect a strong emphasis on AI workflows and agents, positioning Linear as 'The product development system for teams and agents'. Pricing now explicitly lists 'Agent platform' and 'Linear Agent (beta)' on the Free tier, and 'Linear Agent automations (beta)' on the Business tier, indicating a clear strategic shift towards AI-driven product development.",
      "key_changes": [
        "Linear introduced 'Releases' feature for planning and tracking software releases, including CI/CD integration and automated release notes generation. This feature supports up to 15 pipelines on Business plans and unlimited on Enterprise plans.",
        "Linear launched 'Linear Agent MCP support', enabling Linear Agent to connect to external tools (e.g., Granola, Glean, Notion, PostHog) for enhanced context and actions beyond the Linear workspace. This is controlled by allowlists and workspace-level MCP permissions.",
        "The homepage now prominently features 'The product development system for teams and agents' and 'Designed for the AI era', with sections detailing how AI agents are integrated into intake, planning, building, reviewing, and monitoring workflows.",
        "Pricing tiers now explicitly include 'Agent platform' and 'Linear Agent (beta)' in the Free tier, and 'Linear Agent automations (beta)' in the Business tier, formalizing AI features within their product offerings.",
        "Improvements to Linear Agent include the ability to select text anywhere in Linear and send it as context (Cmd+J), and agent chat now opens in a maximized overlay for a more integrated experience."
      ],
      "strategic_signals": [
        "Linear is aggressively leaning into AI as a core differentiator, repositioning itself as an 'AI-first' product development system rather than just an issue tracker. This suggests a belief that AI will fundamentally change how product teams operate.",
        "The introduction of 'Releases' and 'Linear Agent MCP support' indicates a move towards becoming a more comprehensive, end-to-end platform for product development, extending beyond core issue tracking into release management and broader workflow automation via AI.",
        "By offering 'Agent platform' and 'Linear Agent (beta)' on the Free tier, Linear aims to drive early adoption and familiarity with their AI capabilities, potentially creating a strong lock-in effect as users integrate AI into their workflows.",
        "The emphasis on integrating with external tools via MCP suggests Linear wants to be the central hub for product development, leveraging AI to pull in context and trigger actions across a wider ecosystem of tools.",
        "The detailed changelog, especially the numerous fixes and improvements related to Linear Agent, indicates rapid iteration and investment in their AI offerings, suggesting a high priority for this strategic direction."
      ],
      "recommended_actions": [
        "Evaluate our current AI strategy and roadmap. How can we integrate AI more deeply into our core product workflows to compete with Linear's 'AI-first' positioning?",
        "Investigate the 'Linear Agent MCP support' model. Can we develop similar integrations or an 'agent platform' that allows our product to connect with and leverage data from a wider range of external tools?",
        "Review our pricing and packaging for AI features. Should we offer basic AI capabilities on lower tiers to drive adoption, similar to Linear's approach with 'Agent platform' on Free?",
        "Analyze the 'Releases' feature. Does this expose a gap in our current offering? Consider developing or enhancing our own release management capabilities.",
        "Monitor Linear's customer adoption and feedback on their AI features to understand the real-world impact and identify potential competitive advantages or weaknesses."
      ],
      "hiring_signals": [
        "4 new ML/Applied AI engineer roles posted this week (SF + remote) — confirms the 'AI-first' repositioning is fully resourced, not just marketing.",
        "First 'Forward-Deployed Engineer' role opened — Linear is moving toward direct enterprise rollouts, signaling they want to land bigger contracts hands-on.",
        "Two Developer Advocate roles in EMEA — Linear is betting on European developer adoption ahead of any pricing localization move."
      ],
      "urgency": "high"
    },
    "created_at": "2026-05-11 22:07:32"
  },
  {
    "id": 1,
    "competitor": {
      "id": 2,
      "name": "Vercel",
      "domain": "vercel.com"
    },
    "period_start": "2026-05-04T21:34:19.956Z",
    "period_end": "2026-05-11T21:34:19.956Z",
    "urgency": "high",
    "body": {
      "summary": "Vercel has introduced significant new features across its platform, focusing on AI capabilities, advanced deployment strategies, and enhanced network security. Key releases include 'Progressive Rollouts' for Vercel Flags, advanced firewall features for Vercel Sandbox, and expanded Chat SDK support. The homepage and pricing page now prominently feature 'AI Cloud' and related services, indicating a strategic shift towards AI-driven development. The pricing page details new services like Vercel Agent, AI Gateway, and Vercel Workflow, along with granular pricing for existing and new features, including 'Fluid Compute' with Active CPU pricing.",
      "key_changes": [
        "Vercel Flags now support 'Progressive Rollouts', allowing scheduled, gradual feature releases to a growing percentage of users, available in the dashboard and via a new CLI command.",
        "Vercel Sandbox firewall has been enhanced with 'request proxying and filtering' (beta for Pro and Enterprise plans), enabling routing of outbound sandbox traffic through custom proxies and filtering requests based on path, method, query, or headers.",
        "Chat SDK has added support for Messenger and web adapters, facilitating the creation of agents for various chat platforms and browser-based experiences.",
        "The homepage now heavily emphasizes 'AI Cloud' and related products such as Fluid, AISDK, AI Gateway, Workflow, Sandbox, and BotID, signaling a strong strategic focus on AI development.",
        "The pricing page has been updated with detailed pricing for new services like 'Vercel Agent' ($0.30 per action), 'AI Gateway' (observability, image generation, load balancing, etc.), and 'Vercel Workflow' (steps, data retained, data written). It also introduces 'Fluid Compute' with 'Active CPU pricing' for Vercel Functions and Sandbox."
      ],
      "strategic_signals": [
        "Vercel is aggressively moving into the AI development space, positioning itself as an 'AI Cloud' provider, which could attract a new segment of developers and projects focused on AI applications.",
        "The introduction of 'Progressive Rollouts' and advanced Sandbox firewall features indicates a focus on enterprise-grade deployment, security, and experimentation capabilities, catering to larger organizations with complex release cycles and security requirements.",
        "The granular pricing for new AI-related services and 'Active CPU pricing' suggests a shift towards usage-based billing models for compute, potentially optimizing costs for users with fluctuating workloads but also requiring more careful monitoring of spend.",
        "Expanding Chat SDK support aligns with the growing trend of conversational AI and in-product assistants, allowing Vercel to become a more comprehensive platform for building interactive user experiences.",
        "The emphasis on 'Framework-Defined Infrastructure' and 'Deploy once, deliver everywhere' combined with new AI services suggests Vercel aims to be the end-to-end platform for modern web and AI application development, from code to global deployment."
      ],
      "recommended_actions": [
        "Evaluate Vercel's new 'AI Cloud' offerings, particularly 'AI Gateway' and 'Vercel Agent', to understand their competitive advantages and potential impact on our own AI-related product roadmap.",
        "Analyze Vercel's 'Progressive Rollouts' feature and compare it with our existing deployment and experimentation capabilities. Consider if similar functionality could enhance our platform's appeal for enterprise customers.",
        "Review Vercel's updated pricing model, especially 'Active CPU pricing' and the granular costs for new services, to benchmark our own pricing strategies and identify potential areas for optimization or competitive differentiation.",
        "Investigate the Vercel Sandbox firewall's new request proxying and filtering features to understand their security implications and assess if similar advanced network controls are becoming a table stakes requirement for cloud platforms.",
        "Monitor Vercel's adoption rate for their new AI features and Chat SDK adapters to gauge market demand and identify opportunities or threats in the rapidly evolving AI application development landscape."
      ],
      "hiring_signals": [
        "7 AI Cloud / Inference Infra roles opened in the last 7 days — they're scaling the team behind 'Fluid Compute' and 'AI Gateway' rapidly.",
        "First 'Pricing Strategy Manager' role — signals the 'Active CPU' billing experiment is a long-term direction, not a one-off.",
        "Two GTM Enterprise AE roles in NY/London — Vercel is moving upmarket and chasing larger AI-workload contracts."
      ],
      "urgency": "high"
    },
    "created_at": "2026-05-11 21:34:25"
  }
];
