import { getCompetitor, listDigests } from "@/lib/digest";
import { OWNER_WORKSPACE_ID } from "@/lib/auth";
import { DEMO_DIGESTS } from "@/lib/demo-data";
import { stripeHostedUrl } from "@/lib/stripe";
import type { Digest, Competitor } from "@/lib/types";

export const dynamic = "force-dynamic";

interface DemoRow {
  digest: Pick<Digest, "id" | "urgency" | "period_start" | "period_end" | "body">;
  competitor: Pick<Competitor, "id" | "name" | "domain"> | undefined;
}

export default async function Demo() {
  const stripeUrl = stripeHostedUrl();
  const rows: DemoRow[] = [];

  try {
    const live = await listDigests(OWNER_WORKSPACE_ID);
    for (const d of live.slice(0, 3)) {
      rows.push({
        digest: d,
        competitor: await getCompetitor(OWNER_WORKSPACE_ID, d.competitor_id),
      });
    }
  } catch {
    // DB unavailable on serverless cold start — fall through to baked data
  }

  if (rows.length === 0) {
    for (const d of DEMO_DIGESTS.slice(0, 3)) {
      rows.push({ digest: d, competitor: d.competitor });
    }
  }

  if (rows.length === 0) {
    return (
      <div className="card empty-card">
        <div className="empty-title">No demo digests yet</div>
        <div className="empty-body">
          Seed the database with <code>npm run seed</code>, then click{" "}
          <strong>Fetch + Digest</strong> on a competitor in{" "}
          <a href="/app">the dashboard</a>.
        </div>
      </div>
    );
  }

  return (
    <div className="demo">
      <div className="demo-head">
        <div className="hero-eyebrow">live demo · real data</div>
        <h1 className="demo-title">This is what a Monday email looks like.</h1>
        <p className="demo-sub">
          Below are real digests generated by Drift — synthesized by an advanced AI model from
          live competitor pages, formatted exactly as they'd arrive in your inbox.
        </p>
      </div>

      {rows.map(({ digest: d, competitor: c }) => (
        <article key={d.id} className="demo-digest">
          <header className="demo-digest-head">
            <div>
              <h2 className="demo-digest-name">{c?.name ?? "Unknown"}</h2>
              <div className="demo-digest-meta">
                {c?.domain} · {d.period_start.slice(0, 10)} →{" "}
                {d.period_end.slice(0, 10)}
              </div>
            </div>
            <span className={`urgency ${d.urgency}`}>{d.urgency}</span>
          </header>

          <div className="summary-block">{d.body.summary}</div>

          {d.body.key_changes.length > 0 ? (
            <>
              <h3 className="demo-section">Key changes</h3>
              <ul className="demo-list">
                {d.body.key_changes.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </>
          ) : null}

          {d.body.hiring_signals && d.body.hiring_signals.length > 0 ? (
            <>
              <h3 className="demo-section">Hiring signals</h3>
              <ul className="demo-list">
                {d.body.hiring_signals.map((h, i) => (
                  <li key={i}>{h}</li>
                ))}
              </ul>
            </>
          ) : null}

          {d.body.strategic_signals.length > 0 ? (
            <>
              <h3 className="demo-section">Strategic signals</h3>
              <ul className="demo-list">
                {d.body.strategic_signals.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ul>
            </>
          ) : null}

          {d.body.recommended_actions.length > 0 ? (
            <>
              <h3 className="demo-section">Recommended actions</h3>
              <ul className="demo-list">
                {d.body.recommended_actions.map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </>
          ) : null}
        </article>
      ))}

      <section className="demo-cta">
        <h2>This every Monday for your industry?</h2>
        <div className="hero-cta" style={{ justifyContent: "center" }}>
          <a href={stripeUrl} className="btn btn-primary">
            Subscribe — $19/mo
          </a>
          <a
            href="https://github.com/getdrift/drift"
            className="btn btn-secondary"
          >
            Or self-host (free)
          </a>
        </div>
      </section>
    </div>
  );
}
